import src.zadanie6
import src.zadanie7
import src.zadanie8
import src.zadanie9
import src.zadanie10
import src.zadanie11
import src.zadanie12
import src.zadanie13
import src.zadanie14
import src.zadanie15
import src.zadanie16
import src.zadanie17
import src.zadanie18
import src.zadanie19
import src.zadanie20
import src.zadanie21
import src.zadanie22
import src.zadanie23